// Banco de perguntas de conhecimento geral com gabarito.
// Cada entrada possui { q: pergunta, a: resposta curta }.

export const QUESTIONS = {
  facil: [
    { q: "Capital do Brasil?", a: "Brasília" },
    { q: "Cor do céu em um dia ensolarado?", a: "Azul" },
    { q: "Animal que mia?", a: "Gato" },
    { q: "Quanto é 2 + 2?", a: "4" },
    { q: "Fruta amarela rica em potássio?", a: "Banana" },
    { q: "Dia que vem depois de segunda?", a: "Terça-feira" },
    { q: "Planeta em que vivemos?", a: "Terra" },
    { q: "Cor da bandeira do Brasil que não é verde?", a: "Amarelo, azul ou branco" },
    { q: "Principal língua falada no Brasil?", a: "Português" },
    { q: "Animal que late?", a: "Cachorro" },
    { q: "Estação do ano mais quente?", a: "Verão" },
    { q: "Animal que põe ovos e canta ao amanhecer?", a: "Galo" },
    { q: "Profissional que cuida dos dentes?", a: "Dentista" },
    { q: "Objeto usado para escrever no papel?", a: "Caneta" },
    { q: "Aparelho usado para fazer ligações telefônicas?", a: "Celular" },
    { q: "Branco + preto forma qual cor?", a: "Cinza" },
    { q: "Instrumento usado para medir o tempo no pulso?", a: "Relógio" },
    { q: "Principal líquido que bebemos para matar a sede?", a: "Água" },
    { q: "Estrela que ilumina o dia?", a: "Sol" },
    { q: "Meio de transporte que anda sobre trilhos?", a: "Trem" },
    { q: "Maior órgão do corpo humano (externo)?", a: "Pele" },
    { q: "Oposto de quente?", a: "Frio" },
    { q: "Objeto usado para cortar papel?", a: "Tesoura" },
    { q: "Profissional que dá aulas na escola?", a: "Professor" },
    { q: "Animal conhecido como o rei da selva?", a: "Leão" },
    { q: "Metal usado em moedas de um real?", a: "Aço e bronze (bimetálica)" },
    { q: "Inseto que produz mel?", a: "Abelha" },
    { q: "Parte do corpo usada para ver?", a: "Olhos" },
    { q: "Cidade mais famosa da França?", a: "Paris" },
    { q: "Planeta conhecido como planeta vermelho?", a: "Marte" },
    { q: "Dispositivo usado para acessar a internet no bolso?", a: "Smartphone" },
    { q: "Brinquedo com duas rodas e pedal?", a: "Bicicleta" },
    { q: "Animal que dá leite e faz muuu?", a: "Vaca" },
    { q: "Lado onde o sol nasce?", a: "Leste" },
    { q: "Nome do satélite natural da Terra?", a: "Lua" },
    { q: "Animal símbolo da Páscoa?", a: "Coelho" },
    { q: "Fruta vermelha usada em sucos e doces?", a: "Morango" },
    { q: "Animal que tem tromba grande?", a: "Elefante" },
    { q: "Quem pilota um avião?", a: "Piloto" },
    { q: "Objeto usado para apagar lápis?", a: "Borracha" },
    { q: "Oposto de alto?", a: "Baixo" },
    { q: "Animal de estimação que gosta de roer queijo?", a: "Hamster ou rato" },
    { q: "Profissional que cuida de animais?", a: "Veterinário" },
    { q: "Instrumento musical com teclas brancas e pretas?", a: "Piano" },
    { q: "Cor da neve?", a: "Branca" },
    { q: "Objeto usado para ver as horas na parede?", a: "Relógio de parede" },
    { q: "Forma geométrica com três lados?", a: "Triângulo" },
    { q: "Mês do Natal?", a: "Dezembro" },
    { q: "Continente onde fica o Brasil?", a: "América do Sul" },
    { q: "Primeiro dia do ano?", a: "1º de janeiro" },
    { q: "Dia das Bruxas em inglês?", a: "Halloween" },
    // 50 até aqui
    { q: "Animal símbolo do Brasil que vive na Amazônia?", a: "Onça-pintada" },
    { q: "Fruta usada para fazer guacamole?", a: "Abacate" },
    { q: "Líquido vermelho que corre nas veias?", a: "Sangue" },
    { q: "Dia que vem antes de sexta?", a: "Quinta-feira" },
    { q: "Profissional que dirige ônibus?", a: "Motorista" },
    { q: "Alimento feito de milho servido em festas juninas?", a: "Pamonha ou curau" },
    { q: "Brinquedo que voa preso em uma linha?", a: "Pipa" },
    { q: "Oceano que banha o litoral brasileiro?", a: "Atlântico" },
    { q: "Objeto usado para proteger da chuva?", a: "Guarda-chuva" },
    { q: "Profissional que prepara comidas em restaurantes?", a: "Cozinheiro ou chef" },
    { q: "Parte do corpo usada para ouvir?", a: "Orelhas" },
    { q: "Doce feito com leite condensado, chocolate e granulado?", a: "Brigadeiro" },
    { q: "Objeto que usamos para escovar os dentes?", a: "Escova de dentes" },
    { q: "Aparelho usado para assistir filmes em casa?", a: "Televisão" },
    { q: "Esporte mais popular do Brasil?", a: "Futebol" },
    { q: "Animal que diz 'có-có-có'?", a: "Galinha" },
    { q: "Lugar onde moram muitos livros?", a: "Biblioteca" },
    { q: "Cor dos semáforos que significa 'pare'?", a: "Vermelho" },
    { q: "Doce típico enrolado em papel alumínio, feito de coco?", a: "Beijinho" },
    { q: "Profissão de quem apita jogos de futebol?", a: "Árbitro" },
    { q: "País vizinho ao Brasil onde se fala espanhol e tem tango?", a: "Argentina" },
    { q: "Peixe famoso por ser servido cru na culinária japonesa?", a: "Salmão ou atum" },
    { q: "Animal marinho com oito braços?", a: "Polvo" },
    { q: "Frio + água congelada no chão se chama?", a: "Gelo" },
    { q: "Doce feito de amendoim muito comum em festas juninas?", a: "Pé de moleque" },
    { q: "Brinquedo que pula em camas elásticas?", a: "Criança ou pula-pula" },
    { q: "Parte do corpo que usamos para cheirar?", a: "Nariz" },
    { q: "Bebida feita de grãos torrados e água quente?", a: "Café" },
    { q: "Evento que acontece todo ano em fevereiro no Brasil com desfiles?", a: "Carnaval" },
    { q: "Instrumento musical de cordas usado em rodas de samba?", a: "Cavaquinho ou violão" },
    { q: "Material transparente usado em janelas?", a: "Vidro" },
    { q: "Cor que se forma misturando azul e amarelo?", a: "Verde" },
    { q: "Animal que tem cauda longa e gosta de bananas?", a: "Macaco" },
    { q: "Ponto de encontro de aviões em uma cidade?", a: "Aeroporto" },
    { q: "Animal que vive na água e respira por brânquias?", a: "Peixe" },
    { q: "Comida tipicamente italiana em formato de massa com molho?", a: "Macarrão ou espaguete" },
    { q: "Profissão de quem cura doenças das pessoas?", a: "Médico" },
    { q: "Nome do maior estado brasileiro em área?", a: "Amazonas" },
    { q: "Parte da planta que fica debaixo da terra?", a: "Raiz" },
    { q: "Fruta cítrica laranja usada para suco de manhã?", a: "Laranja" },
    { q: "Brinquedo que gira preso a uma cordinha enrolada?", a: "Ioiô" },
    { q: "Lugar da casa onde preparamos comida?", a: "Cozinha" },
    { q: "Doce gelado servido em casquinha ou pote?", a: "Sorvete" },
    { q: "Com quem você dorme quando é bebê e tem medo? (mãe ou pai)", a: "Com os pais" },
    { q: "Parte da roupa usada nos pés para aquecer?", a: "Meia" },
    { q: "Objeto que usamos para pentear o cabelo?", a: "Pente ou escova" },
    { q: "Comida japonesa feita com arroz e peixe enrolados em alga?", a: "Sushi" },
    { q: "Nome do animal símbolo da Austrália que salta?", a: "Canguru" },
    { q: "Objeto usado para iluminar quando falta luz?", a: "Lanterna" },
    { q: "O que usamos para escrever no quadro na escola?", a: "Giz ou marcador" },
    { q: "Nome da estação do ano em que as folhas caem?", a: "Outono" },
    // extras nível fácil
    { q: "Quanto é 10 - 3?", a: "7" },
    { q: "Qual é o maior número: 8 ou 12?", a: "12" },
    { q: "Cor da grama bem cuidada?", a: "Verde" },
    { q: "Animal que faz 'oinc oinc'?", a: "Porco" },
    { q: "Fruta que dá em cacho e pode ser verde, roxa ou vermelha?", a: "Uva" },
    { q: "Qual o continente do Egito?", a: "África" },
    { q: "Qual mês vem depois de março?", a: "Abril" },
    { q: "Qual é o planeta em que existe água líquida em abundância?", a: "Terra" },
    { q: "Objeto usado para ver melhor o que está longe (na praia ou navio)?", a: "Binóculo" },
    { q: "Qual é o animal conhecido por ter uma grande juba?", a: "Leão" },
    { q: "Quantas pernas tem uma aranha?", a: "Oito" },
    { q: "Qual é o nome do maior oceano do planeta?", a: "Oceano Pacífico" },
    { q: "Qual é o número que vem depois do 9?", a: "10" },
    { q: "Qual é o animal que bota ovos e sabe nadar e voar?", a: "Pato" },
    { q: "Qual parte do corpo usamos para sentir o gosto dos alimentos?", a: "Língua" },
    { q: "Qual é o dia da semana em que muitas pessoas descansam, depois do sábado?", a: "Domingo" },
    { q: "Qual estação do ano é conhecida por ter flores brotando?", a: "Primavera" },
    { q: "Qual é o nome do instrumento usado para medir a temperatura?", a: "Termômetro" },
    { q: "Qual é o nome do país onde fica a Amazônia?", a: "Brasil" },
    { q: "Qual é o nome do contorno do nosso corpo projetado na parede pelo sol?", a: "Sombra" },
  ],
  medio: [
    { q: "Capital da Itália?", a: "Roma" },
    { q: "Maior país do mundo em área territorial?", a: "Rússia" },
    { q: "Rio que corta a cidade de Paris?", a: "Sena" },
    { q: "Ano de início da Segunda Guerra Mundial?", a: "1939" },
    { q: "Planeta mais próximo do Sol?", a: "Mercúrio" },
    { q: "Elemento químico representado por O?", a: "Oxigênio" },
    { q: "Língua oficial da Argentina?", a: "Espanhol" },
    { q: "Oceano entre África e Brasil?", a: "Atlântico" },
    { q: "Autor de 'Dom Quixote'?", a: "Miguel de Cervantes" },
    { q: "Capital do Japão?", a: "Tóquio" },
    { q: "Montanha mais alta do mundo?", a: "Everest" },
    { q: "Polígono com cinco lados se chama?", a: "Pentágono" },
    { q: "Músico conhecido como 'Rei do Rock'?", a: "Elvis Presley" },
    { q: "Compositor brasileiro conhecido como 'Rei do Baião'?", a: "Luiz Gonzaga" },
    { q: "Principal gás da atmosfera terrestre?", a: "Nitrogênio" },
    { q: "Ciência que estuda os seres vivos?", a: "Biologia" },
    { q: "Teoria formulada por Charles Darwin?", a: "Teoria da evolução" },
    { q: "País onde se originou o samba?", a: "Brasil" },
    { q: "País de origem da pizza?", a: "Itália" },
    { q: "Pintor famoso pela obra 'Mona Lisa'?", a: "Leonardo da Vinci" },
    { q: "Qual é o maior planeta do Sistema Solar?", a: "Júpiter" },
    { q: "País conhecido como Terra do Sol Nascente?", a: "Japão" },
    { q: "Capital de Minas Gerais?", a: "Belo Horizonte" },
    { q: "Esporte com raquete praticado em quadra com rede baixa?", a: "Tênis" },
    { q: "Cidade-sede do Cristo Redentor?", a: "Rio de Janeiro" },
    { q: "Cientista que formulou a Teoria da Relatividade?", a: "Albert Einstein" },
    { q: "País onde fica a Torre de Pisa?", a: "Itália" },
    { q: "Principal metal do qual é feito o ouro?", a: "Ouro (metal precioso)" },
    { q: "Escritor brasileiro de 'Dom Casmurro'?", a: "Machado de Assis" },
    { q: "Animal símbolo da paz, geralmente branco?", a: "Pomba" },
    { q: "Continente onde fica o Egito?", a: "África" },
    { q: "Capital de Portugal?", a: "Lisboa" },
    { q: "Principal língua falada no Canadá ao lado do inglês?", a: "Francês" },
    { q: "Número de lados de um hexágono?", a: "Seis" },
    { q: "Profissional que estuda o clima e o tempo atmosférico?", a: "Meteorologista" },
    { q: "Continente onde se localiza o Japão?", a: "Ásia" },
    { q: "Nome da galáxia onde está o Sistema Solar?", a: "Via Láctea" },
    { q: "País famoso pelos fiordes e vikings?", a: "Noruega" },
    { q: "País onde se originou o basquete?", a: "Estados Unidos" },
    { q: "Banda britânica famosa pelos álbuns 'Abbey Road' e 'Let It Be'?", a: "The Beatles" },
    { q: "País de origem do filósofo Sócrates?", a: "Grécia" },
    { q: "Animal mamífero que consegue voar?", a: "Morcego" },
    { q: "Principal astro que a Terra orbita?", a: "Sol" },
    { q: "Nome da linha imaginária que divide a Terra em Norte e Sul?", a: "Linha do Equador" },
    { q: "Esporte praticado em piscina com raia?", a: "Natação" },
    { q: "Instrumento de sopro usado em orquestras e bandas marciais?", a: "Trompete ou clarinete" },
    { q: "Nome científico do estudo dos astros?", a: "Astronomia" },
    { q: "País onde se localiza Machu Picchu?", a: "Peru" },
    { q: "Continente com maior número de países?", a: "África" },
    { q: "Maior floresta tropical do mundo?", a: "Floresta Amazônica" },
    // 50 até aqui
    { q: "Capital da Alemanha?", a: "Berlim" },
    { q: "Moeda oficial usada na maior parte da União Europeia?", a: "Euro" },
    { q: "Principal gás responsável pelo efeito estufa?", a: "Dióxido de carbono (CO₂)" },
    { q: "País de origem do físico Albert Einstein?", a: "Alemanha" },
    { q: "Principal órgão responsável pelo bombeamento de sangue?", a: "Coração" },
    { q: "País conhecido pelo tango e pelo churrasco, vizinho do Brasil?", a: "Argentina" },
    { q: "Nome da linha imaginária que divide os fusos horários (meridiano zero)?", a: "Meridiano de Greenwich" },
    { q: "Animal que muda de cor para se camuflar?", a: "Camaleão" },
    { q: "Continente onde se localizam os Andes?", a: "América do Sul" },
    { q: "Nome da embarcação usada pelos portugueses nas Grandes Navegações?", a: "Caravela" },
    { q: "País de origem da Oktoberfest?", a: "Alemanha" },
    { q: "Arte marcial japonesa que utiliza golpes de alavanca e queda?", a: "Judô" },
    { q: "Esporte que usa uma bola oval e capacete, muito popular nos EUA?", a: "Futebol americano" },
    { q: "Nome do processo de transformação da lagarta em borboleta?", a: "Metamorfose" },
    { q: "Doença causada pela carência de vitamina C em marinheiros antigos?", a: "Escorbuto" },
    { q: "Nome do cientista que descobriu a penicilina?", a: "Alexander Fleming" },
    { q: "Continente conhecido como berço da humanidade?", a: "África" },
    { q: "Nome do fenômeno de aquecimento anormal das águas do Pacífico?", a: "El Niño" },
    { q: "Nome do maior deserto quente do mundo?", a: "Saara" },
    { q: "Bebida fermentada feita a partir de cevada e lúpulo?", a: "Cerveja" },
    { q: "Arte japonesa de dobrar papel?", a: "Origami" },
    { q: "Nome da maior ilha do mundo?", a: "Groenlândia" },
    { q: "Nome da nave que levou o homem à Lua na missão Apollo 11?", a: "Apollo 11 (Módulo Eagle)" },
    { q: "País onde se originou o tango?", a: "Argentina" },
    { q: "Nome da única ave que consegue voar para trás com facilidade?", a: "Beija-flor" },
    { q: "País africano conhecido pelas pirâmides antigas?", a: "Egito" },
    { q: "Instrumento usado para medir terremotos?", a: "Sismógrafo" },
    { q: "Ciência que estuda a Terra e sua estrutura?", a: "Geologia" },
    { q: "País asiático famoso por templos budistas e a cidade de Bangkok?", a: "Tailândia" },
    { q: "Instrumento de navegação que indica o norte?", a: "Bússola" },
    { q: "Nome do processo de evaporação e condensação da água na natureza?", a: "Ciclo da água" },
    { q: "Planeta conhecido por seus anéis vistosos?", a: "Saturno" },
    { q: "Nome da primeira fase da vida de um sapo?", a: "Girino" },
    { q: "Animal marinho famoso por sua inteligência e barulhos de clique?", a: "Golfinho" },
    { q: "Nome do órgão responsável pela filtragem do sangue e produção de urina?", a: "Rins" },
    { q: "País onde ocorreu a Revolução Francesa?", a: "França" },
    { q: "Região do Brasil famosa pelo Pantanal?", a: "Centro-Oeste" },
    { q: "Nome da dança típica do Rio Grande do Sul?", a: "Chimarrão não é dança; a dança é a Chula ou Fandango" },
    { q: "Nome da camada gasosa que protege a Terra dos raios ultravioleta?", a: "Camada de ozônio" },
    { q: "Nome da maior cordilheira do mundo?", a: "Cordilheira dos Andes" },
    { q: "Língua falada oficialmente na China?", a: "Mandarim" },
    { q: "País que sediou a Copa do Mundo de 2014?", a: "Brasil" },
    { q: "Nome do famoso físico que propôs a equação E=mc²?", a: "Albert Einstein" },
    { q: "Nome da doença que afeta a taxa de açúcar no sangue (glicose)?", a: "Diabetes" },
    { q: "Nome da famosa cachoeira entre Brasil e Argentina?", a: "Cataratas do Iguaçu" },
    { q: "Nome do maior mamífero terrestre?", a: "Elefante africano" },
    { q: "Nome da arte de cultivar jardins em miniatura, típica do Japão?", a: "Bonsai" },
    { q: "Nome do país que tem a cidade de Moscou como capital?", a: "Rússia" },
    { q: "Nome da escala usada para medir temperatura em graus Celsius?", a: "Escala Celsius" },
    // extras nível médio
    { q: "Capital do estado de São Paulo?", a: "São Paulo" },
    { q: "Qual é o menor continente do mundo em área?", a: "Oceania" },
    { q: "Que nome recebe o processo de transformação da água em vapor?", a: "Evaporação" },
    { q: "Que nome recebe a camada de ar que envolve a Terra?", a: "Atmosfera" },
    { q: "Qual é o único satélite natural da Terra?", a: "Lua" },
    { q: "Em que continente fica o Brasil?", a: "América do Sul" },
    { q: "Qual é o animal mais rápido em terra?", a: "Guepardo" },
    { q: "Qual é o nome do ponto cardeal oposto ao Norte?", a: "Sul" },
    { q: "Que figura geométrica tem quatro lados iguais e quatro ângulos retos?", a: "Quadrado" },
    { q: "Quantos minutos há em uma hora?", a: "60" },
    { q: "Qual é o nome do fenômeno em que a Lua tapa o Sol?", a: "Eclipse solar" },
    { q: "O que estudamos na disciplina de História?", a: "O passado da humanidade" },
    { q: "Como se chama o triângulo que tem todos os lados diferentes?", a: "Escaleno" },
    { q: "Qual é o nome do maior bioma brasileiro, conhecido pela sua biodiversidade e chuvas intensas?", a: "Amazônia" },
    { q: "Em que país nasceu o escritor Monteiro Lobato?", a: "Brasil" },
    { q: "Que nome recebe o conjunto de ossos do corpo humano?", a: "Esqueleto" },
    { q: "Qual é o valor de π (pi) aproximado, com duas casas decimais?", a: "3,14" },
    { q: "Que gás as plantas liberam durante a fotossíntese, importante para a respiração humana?", a: "Oxigênio" },
    { q: "Que instrumento matemático em forma de meia-lua usamos para medir ângulos?", a: "Transferidor" },
    { q: "Em que continente fica o país Índia?", a: "Ásia" },
  ],
  dificil: [
    { q: "Capital da Islândia?", a: "Reykjavik" },
    { q: "Metal líquido à temperatura ambiente, símbolo Hg?", a: "Mercúrio" },
    { q: "Filósofo grego autor da obra 'A República'?", a: "Platão" },
    { q: "País onde se localiza a cidade de Marrakesh?", a: "Marrocos" },
    { q: "Nome da molécula que armazena informação genética nos seres vivos?", a: "DNA" },
    { q: "Língua antiga em que foi escrita boa parte da filosofia clássica ocidental?", a: "Grego antigo" },
    { q: "Compositor da ópera 'A Flauta Mágica'?", a: "Mozart" },
    { q: "Nome do tratado que encerrou a Primeira Guerra Mundial?", a: "Tratado de Versalhes" },
    { q: "Principal filósofo alemão autor de 'Crítica da Razão Pura'?", a: "Immanuel Kant" },
    { q: "Nome da teoria que explica a origem do universo a partir de uma grande explosão?", a: "Teoria do Big Bang" },
    { q: "Nome do processo celular de divisão que gera gametas?", a: "Meiose" },
    { q: "Nome do primeiro satélite artificial lançado ao espaço?", a: "Sputnik 1" },
    { q: "Capital da Nova Zelândia?", a: "Wellington" },
    { q: "Nome da galáxia vizinha da Via Láctea, visível a olho nu?", a: "Galáxia de Andrômeda" },
    { q: "Nome da nave que levou Yuri Gagarin ao espaço?", a: "Vostok 1" },
    { q: "Nome da partícula subatômica sem carga elétrica encontrada no núcleo?", a: "Nêutron" },
    { q: "Nome do pigmento responsável pela cor verde das plantas?", a: "Clorofila" },
    { q: "Nome do movimento artístico de Picasso e Braque no início do século XX?", a: "Cubismo" },
    { q: "Nome do cientista que enunciou as três leis do movimento?", a: "Isaac Newton" },
    { q: "Nome do processo de formação de células sanguíneas na medula óssea?", a: "Hematopoese" },
    { q: "Nome do maior satélite natural de Saturno?", a: "Titã" },
    { q: "Nome da corrente elétrica que não muda de sentido com o tempo?", a: "Corrente contínua" },
    { q: "Nome do país que foi chamado de Pérsia até 1935?", a: "Irã" },
    { q: "Nome do rio mais longo da Ásia?", a: "Rio Yangtzé" },
    { q: "Nome do físico que formulou as leis do eletromagnetismo clássico?", a: "James Clerk Maxwell" },
    { q: "Nome da filosofia oriental baseada nos ensinamentos de Lao-Tsé?", a: "Taoismo" },
    // Removida a pergunta sobre sistema filosófico de Marx e Engels, conforme pedido.
    { q: "Nome da partícula responsável pela força da gravidade segundo o Modelo Padrão (hipotética)?", a: "Gráviton" },
    { q: "Nome da estrutura cerebral associada à memória de longo prazo, em forma de cavalo-marinho?", a: "Hipocampo" },
    { q: "Nome da escala usada para medir a magnitude de terremotos?", a: "Escala Richter" },
    { q: "País europeu conhecido como 'terra dos mil lagos'?", a: "Finlândia" },
    { q: "Nome do fenômeno óptico de desvio de frequência em ondas eletromagnéticas, relacionado à expansão do universo?", a: "Efeito Doppler" },
    { q: "Nome da forma de governo em que o poder é exercido diretamente pelo povo?", a: "Democracia direta" },
    { q: "Nome do cientista polonês que propôs o modelo heliocêntrico?", a: "Nicolau Copérnico" },
    { q: "Nome da molécula que é a principal fonte de energia imediata para as células (sigla)?", a: "ATP" },
    { q: "Nome do principal hormônio produzido pelo pâncreas que regula a glicose?", a: "Insulina" },
    { q: "Nome da guerra que dividiu a península coreana em dois países?", a: "Guerra da Coreia" },
    { q: "Nome do ponto da Terra mais próximo do centro do planeta (não é o Everest)?", a: "Vulcão Chimborazo" },
    { q: "Nome do experimento famoso que demonstrou a dualidade onda-partícula de elétrons?", a: "Experimento da dupla fenda" },
    { q: "Nome da unidade usada para medir a frequência de ondas?", a: "Hertz" },
    { q: "Nome da primeira mulher a ganhar um Prêmio Nobel?", a: "Marie Curie" },
    { q: "Nome da revolução científica ocorrida entre os séculos XVI e XVII na Europa?", a: "Revolução Científica" },
    { q: "Nome do acordo que criou a União Europeia em 1992?", a: "Tratado de Maastricht" },
    { q: "Nome do processo de formação das rochas sedimentares a partir de sedimentos?", a: "Litificação" },
    { q: "Nome do filósofo que escreveu 'Assim Falou Zaratustra'?", a: "Friedrich Nietzsche" },
    { q: "Nome da teoria biológica que explica a origem das células eucariontes a partir de simbiose?", a: "Teoria endossimbiótica" },
    { q: "Nome do processo físico de passagem direta do estado sólido para o gasoso?", a: "Sublimação" },
    // extras nível difícil (ainda dentro de conhecimento geral até 9º ano avançado)
    { q: "Como se chama o conjunto de linhas horizontais e verticais usadas para localizar pontos em um mapa?", a: "Coordenadas geográficas" },
    { q: "Qual é o nome da estrela mais próxima da Terra depois do Sol?", a: "Próxima Centauri" },
    { q: "Como se chama o processo de divisão celular responsável pelo crescimento do corpo?", a: "Mitose" },
    { q: "Qual é o nome da camada mais externa da Terra, onde vivemos?", a: "Crosta terrestre" },
    { q: "Como se chama o movimento de rotação da Terra ao redor de si mesma?", a: "Rotação" },
    { q: "Como se chama o movimento da Terra ao redor do Sol?", a: "Translação" },
    { q: "Que nome recebe o ponto em que dois rios se encontram?", a: "Foz ou confluência" },
    { q: "Qual é a unidade padrão de medida de força no Sistema Internacional?", a: "Newton" },
    { q: "Qual é o nome da ciência que estuda a composição e a estrutura das substâncias?", a: "Química" },
    { q: "Qual é o nome do cientista que propôs as leis da gravitação universal?", a: "Isaac Newton" },
    { q: "Em matemática, como se chama um número que só é divisível por 1 e por ele mesmo?", a: "Número primo" },
    { q: "Em que continente se localiza o deserto do Saara?", a: "África" },
    { q: "Como se chama o ângulo que mede exatamente 90 graus?", a: "Ângulo reto" },
    { q: "Como se chama o conjunto de letras usadas para formar palavras em uma língua?", a: "Alfabeto" },
    { q: "Qual é o nome do gás que os seres humanos eliminam ao expirar?", a: "Gás carbônico ou dióxido de carbono" },
    { q: "Qual é o número que representa a raiz quadrada de 64?", a: "8" },
    { q: "Como se chama o processo de transformação da água líquida em gelo?", a: "Solidificação ou congelamento" },
    { q: "Como se chama o sistema de governo em que o povo elege representantes por meio de voto?", a: "Democracia representativa" },
    { q: "Qual é o nome do continente onde se localizam países como Itália, França e Alemanha?", a: "Europa" },
    { q: "Qual é o nome da propriedade da matéria relacionada à quantidade de matéria em um corpo?", a: "Massa" },
  ],
};

